import type { Metadata } from 'next';
import { loadDevMessages, loadErrorMessages } from '@apollo/client/dev';
import { __DEV__ } from '@apollo/client/utilities/globals';
import { Layout } from '@/components/layout';

export const metadata: Metadata = {
  title: 'Administration',
  description: 'Generated by create next app',
};

if (__DEV__) {
  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}

export default function AdministrationLayout({ children }: { children: React.ReactNode }) {
  return <Layout>{children}</Layout>;
}
