import './globals.css';
import type { Metadata } from 'next';
import { GraphQLProvider } from '@/components/graphql';
import { loadDevMessages, loadErrorMessages } from '@apollo/client/dev';
import { __DEV__ } from '@apollo/client/utilities/globals';
import { EncryptLocalStorageContextProvider, UserContextProvider } from '@/components/utils';
import { Barlow } from 'next/font/google';

const inter = Barlow({ subsets: ['latin'], weight: '200' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

if (__DEV__) {
  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <EncryptLocalStorageContextProvider encryptSecret={process.env.ENCRYPTED_SECRET as string}>
        <UserContextProvider>
          <GraphQLProvider uri={process.env.GRAPHQL_URL as string}>
            <body className={inter.className}>{children}</body>
          </GraphQLProvider>
        </UserContextProvider>
      </EncryptLocalStorageContextProvider>
    </html>
  );
}
